package org.votingsystem.util;

/**
 * Licence: https://github.com/votingsystem/votingsystem/wiki/Licencia
 */
public enum TypeVS {

    ACCESS_REQUEST,
    ITEM_REQUEST,
    ITEMS_REQUEST,
    VOTING_EVENT,

    REPRESENTATIVE_REVOKE,
    NEW_REPRESENTATIVE,
    REPRESENTATIVE,
    ANONYMOUS_REPRESENTATIVE_SELECTION,
    ANONYMOUS_SELECTION_CERT_REQUEST,
    ANONYMOUS_REPRESENTATIVE_SELECTION_CANCELATION,

    PIN,
    EVENT_CANCELLATION,
    BACKUP_REQUEST,
    SEND_VOTE,
    CANCEL_VOTE,
    VOTING_PUBLISHING,

    BROWSER_URL,
    CURRENCY,
    CURRENCY_CANCEL,
    CURRENCY_CHECK,
    FROM_USER,
    CURRENCY_GROUP_NEW,
    CURRENCY_PERIOD_INIT,
    CURRENCY_REQUEST,
    CURRENCY_CHANGE,
    CURRENCY_WALLET_CHANGE,
    CURRENCY_SEND,
    CURRENCY_ACCOUNTS_INFO,
    DEVICE_SELECT,
    TRANSACTION_INFO,
    TRANSACTION_RESPONSE,
    CURRENCY_BATCH,

    FROM_BANK,
    FROM_GROUP_TO_MEMBER_GROUP,
    FROM_GROUP_TO_MEMBER,
    FROM_GROUP_TO_ALL_MEMBERS,
    STATE,

    QR_MESSAGE_INFO,
    QR_MESSAGE_INFO_RESPONSE,

    DELIVERY_WITHOUT_PAYMENT,
    DELIVERY_WITH_PAYMENT,
    REQUEST_FORM,

    MESSAGEVS,
    MESSAGEVS_SIGN,
    MESSAGEVS_SIGN_RESPONSE,
    MSG_TO_DEVICE_BY_TARGET_DEVICE_ID,
    MSG_TO_DEVICE_BY_TARGET_SESSION_ID,
    MESSAGEVS_FROM_VS,

    REPRESENTATIVE_STATE,
    SIGNAL_VS,

    LISTEN_TRANSACTIONS,
    INIT_SESSION,
    INIT_SIGNED_SESSION,
    INIT_BROWSER_AUTHENTICATED_SESSION,
    INIT_REMOTE_SIGNED_SESSION,
    WEB_SOCKET_INIT,
    WEB_SOCKET_CLOSE,
    WEB_SOCKET_BAN_SESSION,
    WEB_SOCKET_REQUEST,
    RECEIPT;

}
